### ISSUE TITLE
Tests for Toolbar occasionally fails

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#349]
Logs:

```
Error: Uncaught [TypeError: Cannot read property 'value' of null]
    at reportException (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
    at innerInvokeEventListeners (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:346:9)
    at invokeEventListeners (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:281:3)
    at HTMLInputElementImpl._dispatch (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:228:9)
    at fireAnEvent (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
    at HTMLInputElementImpl._activationBehavior (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/nodes/HTMLInputElement-impl.js:200:7)
    at HTMLInputElementImpl._dispatch (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:247:26)
    at fireAnEvent (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
    at sendClickToAssociatedNode (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/nodes/HTMLLabelElement-impl.js:12:3)
    at HTMLLabelElementImpl._activationBehavior (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/nodes/HTMLLabelElement-impl.js:87:7)
    at HTMLLabelElementImpl._dispatch (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:247:26)
    at fireAnEvent (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
    at HTMLLabelElementImpl.click (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:77:5)
    at HTMLLabelElement.click (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/generated/HTMLElement.js:80:34)
    at Context.<anonymous> (/home/travis/build/camicroscope/caMicroscope/test/ui/toolbar-test-cases.js:141:23)
    at callFn (/home/travis/build/camicroscope/caMicroscope/node_modules/mocha/lib/runnable.js:395:21)
    at Test.Runnable.run (/home/travis/build/camicroscope/caMicroscope/node_modules/mocha/lib/runnable.js:382:7)
    at Runner.runTest (/home/travis/build/camicroscope/caMicroscope/node_modules/mocha/lib/runner.js:546:10)
    at /home/travis/build/camicroscope/caMicroscope/node_modules/mocha/lib/runner.js:672:12
    at next (/home/travis/build/camicroscope/caMicroscope/node_modules/mocha/lib/runner.js:455:14)
    at /home/travis/build/camicroscope/caMicroscope/node_modules/mocha/lib/runner.js:465:7
    at next (/home/travis/build/camicroscope/caMicroscope/node_modules/mocha/lib/runner.js:367:14)
    at Immediate._onImmediate (/home/travis/build/camicroscope/caMicroscope/node_modules/mocha/lib/runner.js:433:5)
    at processImmediate (internal/timers.js:456:21) TypeError: Cannot read property 'value' of null
    at CaToolbar.getStatus (http://127.0.0.1:8080/components/toolbar/toolbar.js:501:64)
    at innerInvokeEventListeners (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:330:27)
    at invokeEventListeners (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:281:3)
    at HTMLInputElementImpl._dispatch (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:228:9)
    at fireAnEvent (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
    at HTMLInputElementImpl._activationBehavior (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/nodes/HTMLInputElement-impl.js:200:7)
    at HTMLInputElementImpl._dispatch (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:247:26)
    at fireAnEvent (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
    at sendClickToAssociatedNode (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/nodes/HTMLLabelElement-impl.js:12:3)
    at HTMLLabelElementImpl._activationBehavior (/home/travis/build/camicroscope/caMicroscope/node_modules/jsdom/lib/jsdom/living/nodes/HTMLLabelElement-impl.js:87:7)
```

**Comment by cjchirag7** [comment]
I observed this happened in #310  and to pass this test, a did a stricter type checking in the if statement.
